// Generates src/generated/tracers.ts: one lazy import per topic viz.ts (each becomes its own JS chunk).
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const contentDir = path.join(root, 'content');
const entries: [string, string][] = [['playground', '@/components/viz/demo']];

for (const ch of fs.readdirSync(contentDir, { withFileTypes: true })) {
  if (!ch.isDirectory()) continue;
  for (const tp of fs.readdirSync(path.join(contentDir, ch.name), { withFileTypes: true })) {
    if (tp.isDirectory() && fs.existsSync(path.join(contentDir, ch.name, tp.name, 'viz.ts'))) {
      entries.push([`${ch.name}/${tp.name}`, `@content/${ch.name}/${tp.name}/viz`]);
    }
  }
}

const out = `// AUTO-GENERATED by scripts/gen.ts — do not edit.
export const tracerLoaders: Record<string, () => Promise<Record<string, unknown>>> = {
${entries.map(([k, p]) => `  '${k}': () => import('${p}'),`).join('\n')}
};
`;

const file = path.join(root, 'src', 'generated', 'tracers.ts');
fs.mkdirSync(path.dirname(file), { recursive: true });
if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== out) fs.writeFileSync(file, out);
console.log(`gen: ${entries.length} tracer modules`);
