// Generates src/generated/:
//   tracers.ts         one lazy import per topic viz.ts (each becomes its own JS chunk)
//   search-index.json  chapters, topics, examples, practice problems (loaded only when search opens)
import fs from 'node:fs';
import path from 'node:path';
import { getNav, getTopic } from '../src/lib/content';
import { plain, type SearchDoc } from '../src/lib/search';

const root = process.cwd();
const contentDir = path.join(root, 'content');
const outDir = path.join(root, 'src', 'generated');
fs.mkdirSync(outDir, { recursive: true });

function write(file: string, out: string) {
  const p = path.join(outDir, file);
  if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== out) fs.writeFileSync(p, out);
}

// ---------- tracer registry ----------
const entries: [string, string][] = [['playground', '@/components/viz/demo']];
for (const ch of fs.readdirSync(contentDir, { withFileTypes: true })) {
  if (!ch.isDirectory()) continue;
  for (const tp of fs.readdirSync(path.join(contentDir, ch.name), { withFileTypes: true })) {
    if (tp.isDirectory() && fs.existsSync(path.join(contentDir, ch.name, tp.name, 'viz.ts'))) {
      entries.push([`${ch.name}/${tp.name}`, `@content/${ch.name}/${tp.name}/viz`]);
    }
  }
}
write(
  'tracers.ts',
  `// AUTO-GENERATED by scripts/gen.ts — do not edit.
export const tracerLoaders: Record<string, () => Promise<Record<string, unknown>>> = {
${entries.map(([k, p]) => `  '${k}': () => import('${p}'),`).join('\n')}
};
`,
);

// ---------- search index ----------
const docs: SearchDoc[] = [
  { k: 'page', t: 'Patterns pehchano', s: 'Question mein ye keyword dikhe → ye pattern socho', h: '/patterns/', w: 'signals keywords interview kab use karein' },
  { k: 'page', t: 'Bookmarks', s: 'Tumhare save kiye topics', h: '/bookmarks/', w: 'saved star' },
  { k: 'page', t: 'Visualizer playground', s: 'Har animation panel ka demo', h: '/playground/', w: 'animation demo viz' },
];
const sameName = (a: string, b: string) => a.toLowerCase().replace(/[^a-z0-9]/g, '') === b.toLowerCase().replace(/[^a-z0-9]/g, '');
for (const ch of getNav()) {
  docs.push({ k: 'chapter', t: ch.title, s: `Chapter ${ch.index} · ${plain(ch.subtitle)}`, h: ch.href, w: ch.topics.map((x) => x.id).join(' ') });
  for (const nt of ch.topics) {
    if (!nt.available) continue;
    let t;
    try {
      t = getTopic(ch.id, nt.id);
    } catch {
      console.warn(`gen: ${ch.id}/${nt.id} skip (validate error dekho)`);
      continue;
    }
    const where = `${t.meta.title} · Ch ${ch.index}`;
    docs.push({
      k: 'topic',
      t: t.meta.title,
      s: `Ch ${ch.index} · ${ch.title} — ${plain(t.meta.subtitle)}`,
      h: nt.href,
      w: [...t.meta.tags, ...t.when.signals.map((s) => s.keyword)].join(' '),
    });
    for (const ex of t.examples) {
      docs.push({ k: 'example', t: plain(ex.title), s: where, h: `${nt.href}#ex-${ex.id}`, w: ex.source ? `${ex.source.name} ${ex.source.platform}` : '' });
    }
    for (const p of t.practice) {
      if (t.examples.some((ex) => ex.source && sameName(ex.source.name, p.name))) continue; // example hi hai
      const num = p.num ? ` ${p.num}` : '';
      const lc = p.platform === 'LeetCode' && p.num ? ` lc ${p.num} lc${p.num}` : '';
      docs.push({ k: 'problem', t: p.name, s: `${p.platform}${num} · ${where}`, h: `${nt.href}#practice`, w: `${plain(p.pattern)} ${p.level}${lc}` });
    }
  }
}
const json = JSON.stringify(docs);
write('search-index.json', json);
console.log(`gen: ${entries.length} tracer modules, ${docs.length} search docs (${(json.length / 1024).toFixed(0)} KB)`);
